// Types mirroring the items.json generated by scripts/process-items.mjs.

export type Lang = "fr" | "en" | "es" | "pt" | "de";

/** Localised string present for each supported language. */
export type I18nString = Partial<Record<Lang, string>>;

// ─── Effects ──────────────────────────────────────────────────────────────────

export interface MappedEffect {
  /** Effect type id — key into DofusData.effectTypes */
  id: number;
  min: number;
  max?: number;
}

// ─── Conditions ───────────────────────────────────────────────────────────────

export interface MappedConditionLeaf {
  elementId: number;
  operator: string;
  value: number;
}

export interface MappedConditionGroup {
  relation: string;
  children: MappedCondition[];
}

export type MappedCondition = MappedConditionLeaf | MappedConditionGroup;

export function isConditionLeaf(c: MappedCondition): c is MappedConditionLeaf {
  return "elementId" in c;
}

export function isConditionGroup(c: MappedCondition): c is MappedConditionGroup {
  return "children" in c;
}

// ─── Items ────────────────────────────────────────────────────────────────────

export interface MappedItem {
  name: I18nString;
  level: number;
  /** Key into DofusData.itemTypes */
  typeId: number;
  iconId: number;
  /** null when the item belongs to no set */
  setId: number | null;
  effects: MappedEffect[];
  conditions?: MappedCondition;
  apCost?: number;
  minRange?: number;
  range?: number;
  criticalHitProbability?: number;
  criticalHitBonus?: number;
  maxCastPerTurn?: number;
}

// ─── Sets ─────────────────────────────────────────────────────────────────────

export interface MappedSetBonus {
  /** Effect type id */
  id: number;
  value: number;
}

export interface MappedSet {
  name: I18nString;
  level: number;
  /** Ankama item ids that belong to this set */
  items: number[];
  /**
   * Set bonuses keyed by the number of equipped pieces.
   * e.g. { "2": [...], "3": [...] }
   */
  bonuses: Record<string, MappedSetBonus[]>;
}

// ─── Top-level payload ────────────────────────────────────────────────────────

export interface DofusData {
  version: string;
  generatedAt: string;
  /** effectTypeId → localised label */
  effectTypes: Record<number, I18nString>;
  /** itemTypeId → localised label */
  itemTypes: Record<number, I18nString>;
  /** ankama_id → item */
  items: Record<number, MappedItem>;
  /** ankama_id → set */
  sets: Record<number, MappedSet>;
}
